#!/bin/zsh

# Zsh startup file for every shell
# Reference: https://zsh.sourceforge.io/Doc/Release/Files.html

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

if [[ -f "${XDG_CONFIG_HOME}/sh/env.sh" ]]; then
  . "${XDG_CONFIG_HOME}/sh/env.sh"
fi
