# Dracula Color Pallette
white='#f8f8f2'
gray='#44475a'
dark_gray='#282a36'
light_purple='#bd93f9'
dark_purple='#6272a4'
cyan='#8be9fd'
green='#50fa7b'
orange='#ffb86c'
red='#ff5555'
pink='#ff79c6'
yellow='#f1fa8c'

# pane
set-option -g pane-active-border-style "fg=${light_purple}"
set-option -g pane-border-style "fg=${gray}"

# message, status
set-option -g message-style "bg=${gray},fg=${white}"
set-option -g status-style "bg=${gray},fg=${white}"

# left
set-option -g status-left-length 10
set-option -g status-left \
"#[bg=${green},fg=${dark_gray}] #{session_name} "

# window
set-option -g window-status-current-format \
"#[bg=${dark_gray},fg=${white}] #I #W${current_flags} "
set-option -g window-status-format \
"#[bg=${light_purple},fg=${dark_gray}] #I #W${flags} "
set-option -g window-status-separator ""

set-option -g window-status-activity-style "bold"
set-option -g window-status-bell-style "bold"

# right
set-option -g status-right-length 40
set-option -g status-right \
"#[bg=${cyan},fg=${dark_gray}] #{=22:pane_title} \
#[bg=${orange},fg=${dark_gray}] %H:%M %d-%b-%y "

set -s default-terminal "tmux-256color"
set -as terminal-overrides ",*256col*:Tc"
set-option -g history-limit 10000

set-option -g base-index 1
set-option -g pane-base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

set-option -g status-keys vi
set-window-option -g mode-keys vi

bind-key r source-file ~/.tmux.conf
bind-key y set-window-option synchronize-panes

# tmux-in-tmux
%if ${==:${SSH_TTY},}
bind-key C-x if-shell -F "${!=:${key-table},empty}" \
    \
    \
    '\
    set-option key-table empty; \
    set-option message-style "bg=${gray},fg=${white}"; \
    set-option status-style "bg=${gray},fg=${white}"; \
    \
    set-option status-left-length 10; \
    set-option status-left; \
    "#[bg=${green},fg=${dark_gray}] #{session_name} "; \
    \
    set-option window-status-current-format; \
    "#[bg=${dark_gray},fg=${white}] #I #W${current_flags} "; \
    set-option window-status-format; \
    "#[bg=${light_purple},fg=${dark_gray}] #I #W${flags} "; \
    set-option window-status-separator ""; \
    \
    set-option window-status-activity-style "bold"; \
    set-option window-status-bell-style "bold"; \
    \
    set-option status-right-length 40; \
    set-option status-right; \
    "#[bg=${cyan},fg=${dark_gray}] #{=22:pane_title}; \
    #[bg=${orange},fg=${dark_gray}] %H:%M %d-%b-%y "; \
    ' \
    \
    \
    'set-option -u key-table;'
bind-key -T empty C-x switch-client -T prefix
%endif

