set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'  

set -g @dracula-show-fahrenheit false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-border-contrast true

run '~/.tmux/plugins/tpm/tpm'

set -s default-terminal "tmux-256color"
set -as terminal-overrides ",*256col*:Tc"
set-option -g history-limit 10000

set-option -g base-index 1
set-option -g pane-base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

set-option -g status-keys vi
set-window-option -g mode-keys vi
set-window-option -g monitor-activity on

bind-key r source-file ~/.tmux.conf
bind-key y set-window-option synchronize-panes

