tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "bat"
brew "cask"
brew "cmatrix"
brew "cowsay"
brew "fzf"
brew "python@3.9"
brew "glib"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "mas"
brew "neofetch"
brew "node"
brew "openjdk"
brew "ruby"
brew "tldr"
brew "tmux"
brew "vim"
brew "zplug"
brew "zsh"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "chrome-remote-desktop-host"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "iterm2"
cask "macs-fan-control"
cask "mactex"
cask "nosleep"
cask "notion"
cask "sublime-text"
cask "the-unarchiver"
cask "ubersicht"
cask "vlc"
cask "vox"
cask "zoom"
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "카카오톡", id: 869223134
