#!/bin/bash

set nounset
set errexit
shopt -s nullglob

# Print a trace of commands
# set -o xtrace # (= `set -x`)

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
# Get base directory (e.g., `$HOME/dotfiles`)
basedir="$(realpath "$(dirname "$0")")"
# Get OS name (e.g., Darwin)
os="$(uname -s)"

# Update dotfiles
# command -v git > /dev/null && (cd "$basedir" && git pull origin main);

echoerr() { echo $@ 1>&2; }

symlink_home() {
  local source_file="$1"

  # If the source file not exists, return with an error
  if [[ ! -e "${source_file}" ]]; then return 1; fi
  local target_file
  target_file="${HOME}/$(basename "$source_file")"

  # If the existing target is a symlink to the source file, return
  if [[ -L "${target_file}" ]] &&
    [[ $(readlink "${target_file}") == "${source_file}" ]]; then
      return 0;
  fi

  # If the target file exists, ask to replace or not
  if [[ -e "${target_file}" ]]; then

    local opt
    echo "File \"${target_file}\" already exists!"
    read -rp \
      "[O]verwrite the file, (B)ackup, (S)kip: " opt
          case ${opt} in
            [Oo] | "" ) rm -rf "${target_file}" ;;
            [Bb] ) mv "${target_file}" "${target_file}.$(date +%s)" ;;
            [Ss] ) return 0 ;;
            * ) return 1 ;;
          esac
  fi

  # Make a target symlink verbosely
  ln -sfn "${source_file}" "${target_file}"
  echoerr "${target_file} -> ${source_file}"
  return 0
}

# Array of common dotfiles
dotfiles_common=(
  "${basedir}/bash/.bash_profile"
  "${basedir}/bash/.bashrc"
  "${basedir}/bash/.bashrc.d/"
  "${basedir}/etc/.inputrc"
  "${basedir}/sh/.profile"
  "${basedir}/sh/.shrc"
  "${basedir}/sh/.shrc.d/"
  "${basedir}/vim/.vim/"
  "${basedir}/zsh/.zshrc"
  "${basedir}/zsh/.zshrc.d/"
)

echoerr "Make symbolic links of common dotfiles..."
for dotfile in "${dotfiles_common[@]}"; do
  symlink_home "${dotfile}" || true
done
unset dotfile
echoerr "Done."

for i in ${basedir}/setup.d/*; do
  echoerr "Run $i"
  $i
done

mkdir -p "${XDG_CONFIG_HOME}"
for i in ${basedir}/xdg_config_home/*; do
  echoerr "$i -> ${XDG_CONFIG_HOME}/$(basename $i)"
  ln -sfn "$i" "${XDG_CONFIG_HOME}/$(basename $i)"
done
unset i

echoerr "Set configurations for ${os}."
os_setup="${basedir}/setup.os/setup##os.${os}"
[[ -e "${os_setup}" ]] && "${os_setup}"

echo "Restart your login shell with \`exec \"\${SHELL}\" --login\`"
