#!/bin/bash

set -o nounset
set -o errexit
shopt -s nullglob

FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      echo "Usage: $(basename $0) [options]"
      echo "Options:"
      echo "  -h, --help    Show this help message and exit"
      echo "  -f, --force   Force overwrite existing files"
      exit 0
      ;;
    --)
      break
      ;;
    -f|--force)
      FORCE=1
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
  shift
done

echoerr() { echo "$@" 1>&2; }
export -f echoerr

if [[ $FORCE -eq 1 ]]; then
  LNFLAGS="-svnf"
  RMFLAGS="-rvf"
else
  LNFLAGS="-svni"
  RMFLAGS="-rvi"
fi

# Get base directory (e.g., `$HOME/dotfiles`)
basedir="$(realpath "$(dirname "$0")")"
# Get OS name (e.g., Darwin)
os="$(uname -s)"

export LNFLAGS
export RMFLAGS
export basedir
export os

# shellcheck source=/dev/null
source "${basedir}/env"

ln "${LNFLAGS}" "${basedir}/env" "${HOME}/.shenv"

# XXX: Is it necessary?
[ -e "${HOME}/.config" ] && rm ${RMFLAGS} "${HOME}/.config"
ln ${LNFLAGS} "${basedir}/xdg-config-home" "${HOME}/.config"

ln ${LNFLAGS} "${basedir}/xdg-config-home/bash/bash_profile" "${HOME}/.bash_profile"
ln ${LNFLAGS} "${basedir}/xdg-config-home/bash/bashrc" "${HOME}/.bashrc"
ln ${LNFLAGS} "${basedir}/xdg-config-home/git/gitmessage" "${HOME}/.gitmessage"
ln ${LNFLAGS} "${basedir}/xdg-config-home/sh/profile" "${HOME}/.profile"
ln ${LNFLAGS} "${basedir}/xdg-config-home/tmux/tmux.conf" "${HOME}/.tmux.conf"
ln ${LNFLAGS} "${basedir}/xdg-config-home/vim/vimrc" "${HOME}/.vimrc"
ln ${LNFLAGS} "${basedir}/xdg-config-home/zsh/zprofile" "${XDG_CONFIG_HOME}/zsh/.zprofile"
ln ${LNFLAGS} "${basedir}/xdg-config-home/zsh/zshenv" "${HOME}/.zshenv"
ln ${LNFLAGS} "${basedir}/xdg-config-home/zsh/zshrc" "${XDG_CONFIG_HOME}/zsh/.zshrc"

LOCAL_GITCONFIG="${HOME}/.gitconfig.local"
if [ ! -f "${LOCAL_GITCONFIG}" ]; then
  read -r -p "Do you want to create a local gitconfig file at ${LOCAL_GITCONFIG}? [Y/n] " yn
  case ${yn} in
    [Yy] | "" )
      read -r -p "Enter your git user name: " git_username
      read -r -p "Enter your git user email: " git_useremail
      cat <<EOF > "${LOCAL_GITCONFIG}"
[user]
  name = ${git_username}
  email = ${git_useremail}
EOF
  ;;
  esac
fi

XDG_BIN_HOME="${HOME}/.local/bin"
mkdir -p "${XDG_BIN_HOME}"
ln ${LNFLAGS} "${basedir}/scripts"/* ${XDG_BIN_HOME}

GIT_COMPLETION_DIR="${XDG_DATA_HOME}/git/completion"
GIT_PROMPT_URL="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
mkdir -p "${GIT_COMPLETION_DIR}"
curl -L "${GIT_PROMPT_URL}" -o "${GIT_COMPLETION_DIR}/git-prompt.sh"
unset GIT_PROMPT_URL
unset GIT_COMPLETION_DIR

WEZTERM_SHELL_INTEGRATION_URL="https://raw.githubusercontent.com/wezterm/wezterm/main/assets/shell-integration/wezterm.sh"
WEZTERM_SHELL_INTEGRATION_DIR="${XDG_DATA_HOME}/wezterm/shell-integration"
mkdir -p "${WEZTERM_SHELL_INTEGRATION_DIR}"
curl -L "${WEZTERM_SHELL_INTEGRATION_URL}" -o "${WEZTERM_SHELL_INTEGRATION_DIR}/wezterm.sh"
unset WEZTERM_SHELL_INTEGRATION_URL
unset WEZTERM_SHELL_INTEGRATION_DIR

if ! command mise -v 2> /dev/null; then
  curl "https://mise.run" | sh
  eval "$("${HOME}/.local/bin/mise" activate bash)"
fi

command mise -v 2> /dev/null && mise install

os_setup="${basedir}/setup.os/setup#os.${os}"
if [[ -f "${os_setup}" ]]; then
  read -r -p "Do you want to set configurations for ${os}? [Y/n] " yn
  case ${yn} in
    [Yy] | "" ) "${os_setup}" ;;
  esac
fi

echo "Restart your login shell with \`exec \"\${SHELL}\" --login\`"
