#!/bin/bash

set -o nounset
set -o errexit
shopt -s nullglob

FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      echo "Usage: $(basename $0) [options]"
      echo "Options:"
      echo "  -h, --help    Show this help message and exit"
      echo "  -f, --force   Force overwrite existing files"
      exit 0
      ;;
    --)
      break
      ;;
    -f|--force)
      FORCE=1
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
  shift
done

echoerr() { echo "$@" 1>&2; }
export -f echoerr

if [[ $FORCE -eq 1 ]]; then
  LNFLAGS="-svf"
  RMFLAGS="-rvf"
else
  LNFLAGS="-svi"
  RMFLAGS="-rvi"
fi

# Get base directory (e.g., `$HOME/dotfiles`)
basedir="$(realpath "$(dirname "$0")")"
# Get OS name (e.g., Darwin)
os="$(uname -s)"

export basedir
export os

# shellcheck source=/dev/null
source "${basedir}/env"

ln $LNFLAGS "${basedir}/env" "${HOME}/.shenv"

rm $RMFLAGS "${HOME}/.config"
ln $LNFLAGS "${basedir}/xdg_config_home" "${HOME}/.config"

ln $LNFLAGS "${basedir}/xdg_config_home/bash/bash_profile" "${HOME}/.bash_profile"
ln $LNFLAGS "${basedir}/xdg_config_home/bash/bashrc" "${HOME}/.bashrc"
ln $LNFLAGS "${basedir}/xdg_config_home/git/gitmessage" "${HOME}/.gitmessage"
ln $LNFLAGS "${basedir}/xdg_config_home/sh/profile" "${HOME}/.profile"
ln $LNFLAGS "${basedir}/xdg_config_home/tmux/tmux.conf" "${HOME}/.tmux.conf"
ln $LNFLAGS "${basedir}/xdg_config_home/vim/vimrc" "${HOME}/.vimrc"
ln $LNFLAGS "${basedir}/xdg_config_home/zsh/zprofile" "${XDG_CONFIG_HOME}/zsh/.zprofile"
ln $LNFLAGS "${basedir}/xdg_config_home/zsh/zshenv" "${HOME}/.zshenv"
ln $LNFLAGS "${basedir}/xdg_config_home/zsh/zshrc" "${XDG_CONFIG_HOME}/zsh/.zshrc"

XDG_BIN_HOME="${HOME}/.local/bin"
ln $LNFLAGS "${basedir}/scripts"/* ${XDG_BIN_HOME}

os_setup="${basedir}/setup.os/setup##os.${os}"
if [[ -e "${os_setup}" ]]; then
  read -r -p "Do you want to set configurations for ${os}? [Y/n] " yn
  case $yn in
    [Yy] | "" )
      echoerr "Run ${os_setup}"
      "${os_setup}"
    ;;
    [Nn] ) ;;
    * ) exit 1;;
  esac
fi

echo "Restart your login shell with \`exec \"\${SHELL}\" --login\`"
