vim.pack.add({
	"https://github.com/junegunn/fzf",
	"https://github.com/junegunn/fzf.vim",
	"https://github.com/lewis6991/gitsigns.nvim",
	"https://github.com/tpope/vim-fugitive",
	"https://github.com/tpope/vim-obsession",
	"https://github.com/tpope/vim-surround",
	"https://github.com/tpope/vim-repeat",
	"https://github.com/tpope/vim-abolish",
	"https://github.com/tpope/vim-unimpaired",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/tpope/vim-projectionist",
	"https://github.com/github/copilot.vim",
	"https://github.com/lervag/vimtex",
	"https://github.com/folke/which-key.nvim",
})

require("plugins.lsp")
require("plugins.fzf")
require("plugins.copilot")
require("plugins.git")
require("plugins.session")
require("plugins.vimtex")
require("plugins.oil")
require("plugins.projectionist")
require("plugins.which-key")
