#!/bin/bash

[[ -e "${HOME}/.shenv" ]] && ENV="${HOME}/.shenv"
export ENV
# shellcheck source=/dev/null
[[ -n $ENV ]] && source "$ENV"

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
BASHRC="${XDG_CONFIG_HOME}/bash/bashrc"
# shellcheck source=/dev/null
[[ -e "${BASHRC}" ]] && source "${BASHRC}"
