#!/bin/sh

# POSIX shell startup file for an interactive login shell

[ -e "${HOME}/.shenv" ] && ENV="${HOME}/.shenv"
export ENV
# shellcheck source=/dev/null
[ -n "$ENV" ] && . "$ENV"

: "${XDG_BIN_HOME:="${HOME}/.local/bin"}"
: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
PATH=${XDG_BIN_HOME}:$PATH

# Set locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Export editors
export EDITOR='vim -E'
export PAGER='less'
export VISUAL='vim'

# Cygwin environment variables
# https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
export CYGWIN=winsymlinks:nativestrict
export MSYS="${CYGWIN}"
