#!/bin/sh

# POSIX shell startup file for an interactive login shell

[[ -e "${HOME}/.shenv" ]] && ENV="${HOME}/.shenv"
export ENV
[[ -n $ENV ]] && source "$ENV"

: ${XDG_BIN_HOME:="${HOME}/.local/bin"}
: ${XDG_CONFIG_HOME:="${HOME}/.config"}
PATH=${XDG_BIN_HOME}:$PATH

# Set locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Export editors
export VISUAL='vim'
export EDITOR='vim -E'
export PAGER='less'
export MANPAGER='less -R --use-color -Dd+r -Du+g'

export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"

# Cygwin environment variables
# https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
export CYGWIN=winsymlinks:nativestrict
export MSYS="${CYGWIN}"
