" :help xdg-base-dir
if empty("$XDG_CACHE_HOME") | let $XDG_CACHE_HOME="$HOME/.cache" | endif
if empty("$XDG_CONFIG_HOME") | let $XDG_CONFIG_HOME="$HOME/.config" | endif
if empty("$XDG_DATA_HOME") | let $XDG_DATA_HOME="$HOME/.local/share" | endif
if empty("$XDG_STATE_HOME") | let $XDG_STATE_HOME="$HOME/.local/state" | endif

set runtimepath=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$VIM
set runtimepath+=$VIMRUNTIME

set packpath=$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after
set packpath+=$VIM
set packpath+=$VIMRUNTIME

let $MYVIMRC = $XDG_CONFIG_HOME . '/vim/vimrc'
source $MYVIMRC
