#!/bin/zsh

# Zsh startup file for every shell
# https://zsh.sourceforge.io/Intro/intro_3.html

[[ -e "${HOME}/.shenv" ]] && ENV="${HOME}/.shenv"
export ENV
[[ -n $ENV ]] && source "$ENV"

: ${XDG_CONFIG_HOME:="${HOME}/.config"}

ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZDOTDIR
