#!/bin/bash
# Bash startup file for login shells
# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

# Source the shell-independent startup file for login shells
# shellcheck source=/dev/null
[[ -f "${HOME}/.profile" ]] && source "${HOME}/.profile";

# Source the bash startup file for non-login shells
# shellcheck source=/dev/null
[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc";
