#!/bin/sh
# Shell-independent startup file for login shells

# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"

# User specific environment
PATH="${HOME}/.local/bin:${PATH}"
export PATH

# Set locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Export editors
export VISUAL='vim';
export EDITOR='vim -E';
export PAGER='less';

# Cygwin environment variables
# https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
export CYGWIN=winsymlinks:nativestrict
export MSYS="${CYGWIN}"

ENV="${HOME}/.shrc"; export ENV
