" ~/.vim/vimrc
" :help :help
" https://learnvimscriptthehardway.stevelosh.com
" https://learnvim.irian.to

" :help xdg-base-dir
if empty("$XDG_CACHE_HOME") | let $XDG_CACHE_HOME="$HOME/.cache" | endif
if empty("$XDG_CONFIG_HOME") | let $XDG_CONFIG_HOME="$HOME/.config" | endif
if empty("$XDG_DATA_HOME") | let $XDG_DATA_HOME="$HOME/.local/share" | endif
if empty("$XDG_STATE_HOME") | let $XDG_STATE_HOME="$HOME/.local/state" | endif

set runtimepath=$HOME/.vim
set runtimepath+=$XDG_CONFIG_HOME/vim
set runtimepath+=$VIM/vimfiles
set runtimepath+=$VIMRUNTIME
set runtimepath+=$VIM/vimfiles/after
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$HOME/.vim/after

set packpath=$HOME/.vim
set packpath+=$XDG_CONFIG_HOME/vim
set packpath+=$VIM/vimfiles
set packpath+=$VIMRUNTIME
set packpath+=$VIM/vimfiles/after
set packpath+=$XDG_CONFIG_HOME/vim/after
set packpath+=$HOME/.vim/after

let $MYVIMRC = $XDG_CONFIG_HOME . '/vim/vimrc'

if empty(glob($XDG_CONFIG_HOME . '/vim/autoload/plug.vim'))
  silent execute '!curl -fLo '
        \.$XDG_CONFIG_HOME
        \.'/vim/autoload/plug.vim '
        \.'--create-dirs '
        \.'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin($XDG_DATA_HOME . '/vim/plugged')
Plug 'junegunn/vim-plug'

Plug 'junegunn/fzf', {'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'

Plug 'rhysd/vim-healthcheck'
Plug 'airblade/vim-gitgutter'
Plug 'github/copilot.vim'

Plug 'DingDean/wgsl.vim'
call plug#end()

packadd! bufferline
packadd! sensible
packadd! statusline
packadd! unimpaired
packadd! vim-scriptease
packadd! vim-templates

silent! colorscheme dracula16

" :help mapleader
let mapleader = "\<space>"

" Source files in vimrc.d
for s:f in split(glob('$XDG_CONFIG_HOME/vim/vimrc.d/*.vim'), '\n')
  execute 'source ' . s:f
endfor

" :help 'termguicolors'
" if has('termguicolors') | set termguicolors | endif

" :help xterm-true-color
let &t_8f="\<esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<esc>[48;2;%lu;%lu;%lum"

" :help termcap-cursor-shape
let &t_SI="\<esc>[5 q" " blinking bar
let &t_SR="\<esc>[3 q" " blinking underline
let &t_EI="\<esc>[2 q" " steady block

augroup termcap_cursor_shape
  autocmd!
  autocmd VimEnter * silent execute 'silent !echo -ne "\e[2 q"'
  if exists('##VimResume')
    autocmd VimResume * silent execute 'silent !echo -ne "\e[2 q"' | redraw!
  endif
augroup END

" :help checktime
augroup checktime
  autocmd!
  if exists('##VimResume')
    autocmd VimResume * checktime
  endif
augroup END

" https://github.com/vim/vim/commit/e07e797db0c5ef1aafc650d8bb0d39fb052cf1e1
set ttimeout
set ttimeoutlen=100

" :help section
map [[ ?{<cr>w99[{
  map ][ /{<cr>b99[{
  map ]] j0[[%/{<cr>
map [] k$][%?}<cr>

" :help 'colorcolumn'
if exists('&colorcolumn') | set colorcolumn=+2 | endif

" :help :helptags
" XXX: Long startup time
" silent! helptags ALL

set number
set relativenumber
set ignorecase
set smartcase
set list
set visualbell
set nowrap
set foldlevel=99

" :help xdg-base-dir
set backupdir=$XDG_STATE_HOME/vim/backup
set directory=$XDG_STATE_HOME/vim/swap
if has('persistent_undo') | set undodir=$XDG_STATE_HOME/vim/undo | endif
if has('viminfo') | set viminfo+=n$XDG_STATE_HOME/vim/viminfo | endif
" set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after
" set runtimepath+=$VIM,$VIMRUNTIME
let &spellfile = expand('$XDG_DATA_HOME/vim/spell/en.utf-8.add')
let s:spelldir = fnamemodify(&spellfile, ':p:h')
if !isdirectory(s:spelldir) | call mkdir(s:spelldir, 'p') | endif
if has('persistent_undo') | set undofile | endif
if has('syntax') | set spell | endif

" :help g:netrw_home
" :help .netrwhist
let g:netrw_home = expand('$XDG_STATE_HOME/vim/netrw')

cabbr <expr> %% expand('%:p:h')

xnoremap < <gv
xnoremap > >gv

if !has('nvim') && exists('*TerminalWinOpen')
  augroup terminal_win_open
    autocmd!
    autocmd TerminalWinOpen *
          \ setlocal nobuflisted
          \|setlocal nospell
          \|setlocal colorcolumn=
  augroup end
endif

" source local vimrc
let s:vimrc_local = expand('$HOME/.vimrc.local')
if filereadable(s:vimrc_local) | execute "source " . s:vimrc_local | endif

" :help wildmode
set wildmode=longest,full


" :help <leader>
" See more
" ~/.vim/vimrc.d/recommendations.vim
" ~/.vim/vimrc.d/fzf.vim
nnoremap <silent> <leader>= mzHmygg=G'yz<cr>`z
nnoremap <leader>mm :<c-u>make!<cr>
nnoremap <leader>ma :<c-u>make! all<cr>
nnoremap <leader>mc :<c-u>make! clean<cr>
nnoremap <leader>mr :<c-u>make! run<cr>
nnoremap <leader>mi :<c-u>make! install<cr>
nnoremap <leader>m<space> :<c-u>make!<space>

nnoremap <leader>cc :<c-u>cclose<cr>

nnoremap <leader>hc :<c-u>helpclose<cr>

nnoremap <leader>vv :<c-u>edit $MYVIMRC<cr>
nnoremap <leader>vV :<c-u>execute 'edit ' . fnamemodify($MYVIMRC, ':h')<cr>
nnoremap <leader>vd :<c-u>edit $MYVIMRC.d<cr>
nnoremap <leader>vr :<c-u>Reload<cr>


" :help ins-completion
function! SmartInsertCompletion()
  if pumvisible()
    return "\<c-n>"
  elseif !empty(&omnifunc)
    return "\<c-x>\<c-u>"
  endif
  return "\<c-n>"
endfunction
" inoremap <silent> <c-n> <c-r>=SmartInsertCompletion()<cr>


" :help 'completeopt'
set completeopt+=menuone,noinsert
set completepopup=height:10,width:60

" :help last-pattern
let @/ = ""

autocmd BufWinEnter *
      \ if line2byte(line("$") + 1) > 1000000 | syntax clear | endif

set showtabline=1
set lazyredraw
command! Reload source $MYVIMRC | echo "Reloaded"

autocmd BufWritePre "." echo "Filename is ."
