" ~/.vim/vimrc
" :help :help
" https://learnvimscriptthehardway.stevelosh.com
" https://learnvim.irian.to

if &g:compatible
  set nocompatible
endif

set packpath+=$XDG_DATA_HOME/vim
let s:minpac_dir = expand('$XDG_DATA_HOME/vim')
let s:minpac_config = {'dir': s:minpac_dir, 'progress_open': 'none'}

silent! packadd minpac
if exists('g:loaded_minpac')
  function! s:PackInit() abort
    call minpac#init(s:minpac_config)
    call minpac#add('k-takata/minpac', {'type': 'opt'})

    call minpac#add('airblade/vim-gitgutter')

    call minpac#add('github/copilot.vim')

    call minpac#add('junegunn/fzf', {'do': { -> fzf#install() } })
    call minpac#add('junegunn/fzf.vim')

    " call minpac#add('mattn/vim-lsp-settings')
    " call minpac#add('prabirshrestha/asyncomplete-lsp.vim')
    " call minpac#add('prabirshrestha/asyncomplete.vim')
    call minpac#add('prabirshrestha/vim-lsp')

    " call minpac#add('takac/vim-hardtime')

    " call minpac#add('tpope/vim-abolish')
    call minpac#add('tpope/vim-commentary')
    call minpac#add('tpope/vim-fugitive')
    call minpac#add('tpope/vim-repeat')
    call minpac#add('tpope/vim-surround')
    call minpac#add('tpope/vim-vinegar')
    " call minpac#add('tpope/vim-dispatch')
  endfunction

  command! PackUpdate
        \ source $MYVIMRC | call s:PackInit() | call minpac#update()
  command! PackClean
        \ source $MYVIMRC | call s:PackInit() | call minpac#clean()
  command! PackStatus call minpac#status()
endif

silent! colorscheme dracula16

" Source files in vimrc.d
for s:f in split(glob('$XDG_CONFIG_HOME/vim/vimrc.d/*.vim'), '\n')
  execute 'source ' . s:f
endfor

" :help 'termguicolors'
" if has('termguicolors') | set termguicolors | endif

" :help xterm-true-color
let &t_8f="\<esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<esc>[48;2;%lu;%lu;%lum"

" :help termcap-cursor-shape
let &t_SI="\<esc>[5 q" " blinking bar
let &t_SR="\<esc>[3 q" " blinking underline
let &t_EI="\<esc>[2 q" " steady block

augroup termcap_cursor_shape
  autocmd!
  autocmd VimEnter * silent execute 'silent !echo -ne "\e[2 q"' | redraw!
  if exists('##VimResume')
    autocmd VimResume * silent execute 'silent !echo -ne "\e[2 q"' | redraw!
  endif
augroup END

augroup checktime
  autocmd!
  if exists('##VimResume')
    autocmd VimResume * checktime
  endif
augroup END

" https://github.com/vim/vim/commit/e07e797db0c5ef1aafc650d8bb0d39fb052cf1e1
set ttimeout
set ttimeoutlen=100

" :help section
map [[ ?{<cr>w99[{
map ][ /{<cr>b99[{
map ]] j0[[%/{<cr>
map [] k$][%?}<cr>

" :help 'colorcolumn'
if exists('&colorcolumn') | set colorcolumn=81 | endif

" :help :helptags
" XXX: Long startup time
" silent! helptags ALL

set number
set relativenumber
set ignorecase
set smartcase
set list
set visualbell
set nowrap
set foldlevel=99

" :help xdg-base-dir
set backupdir=$XDG_STATE_HOME/vim/backup
set directory=$XDG_STATE_HOME/vim/swap
if has('persistent_undo') | set undodir=$XDG_STATE_HOME/vim/undo | endif
if has('viminfo') | set viminfo+=n$XDG_STATE_HOME/vim/viminfo | endif
" set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after
" set runtimepath+=$VIM,$VIMRUNTIME
let &spellfile = expand('$XDG_DATA_HOME/vim/spell/en.utf-8.add')
let s:spelldir = fnamemodify(&spellfile, ':p:h')
if !isdirectory(s:spelldir) | call mkdir(s:spelldir, 'p') | endif
if has('persistent_undo') | set undofile | endif
if has('syntax') | set spell | endif

" :help g:netrw_home
" :help .netrwhist
let g:netrw_home = expand('$HOME/.cache')

cabbr <expr> %% expand('%:p:h')

xnoremap < <gv
xnoremap > >gv

if !has('nvim') && exists('*TerminalWinOpen')
  augroup terminal_win_open
    autocmd!
    autocmd TerminalWinOpen *
          \ setlocal nobuflisted
          \|setlocal nospell
          \|setlocal colorcolumn=
  augroup end
endif

" source local vimrc
let s:vimrc_local = expand('$HOME/.vimrc.local')
if filereadable(s:vimrc_local) | execute "source " . s:vimrc_local | endif

" :help wildmode
set wildmode=longest,full

" :help <leader>
" See more
" ~/.vim/vimrc.d/recommendations.vim
" ~/.vim/vimrc.d/fzf.vim
let mapleader = "\<Space>"
nnoremap <silent> <leader>= mzHmygg=G'yz<cr>`z
nnoremap <leader>mm :<c-u>make!<cr>
nnoremap <leader>mc :<c-u>make! clean<cr>
nnoremap <leader>mr :<c-u>make! run<cr>
nnoremap <leader>mi :<c-u>make! install<cr>

nnoremap <leader>cc :<c-u>cclose<cr>

nnoremap <leader>vv :<c-u>edit $MYVIMRC<cr>
nnoremap <leader>vd :<c-u>edit $MYVIMRC.d<cr>
nnoremap <leader>vp :<c-u>edit ~/.vim/pack<cr>
nnoremap <leader>vr :<c-u>Reload<cr>

" :help last-pattern
let @/ = ""

if exists(':PackUpdate') != 0 && exists(':PackClean') != 0
  augroup pack_update
    autocmd!
    autocmd VimEnter * silent! PackUpdate
    autocmd VimEnter * silent! PackClean
  augroup END
endif

autocmd BufWinEnter *
      \ if line2byte(line("$") + 1) > 1000000 | syntax clear | endif

command! Reload source $MYVIMRC
