#!/bin/sh
# Shell-independent startup file for an interactive shell

export MANPAGER="less"
export NOW_PLAYING_WIDGET_HOOK='nowplaying-cli get artworkData \
  | base64 -d \
  | colorgen - \
  | flavours apply --stdin \
'

if [ -n "${WEZTERM_EXECUTABLE}" ]; then
  export WEZTERM_SHELL="${SHELL}"
else
  if [ -f "${XDG_STATE_HOME}"/sh/colors.sh ]; then
    # shellcheck source=/dev/null
    case $- in
      *i*) . "${XDG_STATE_HOME}"/sh/colors.sh ;;
    esac
  fi
fi

SHRCDIR="${XDG_CONFIG_HOME}/sh/shrc.d"
if [ -d "${SHRCDIR}" ]; then
  for sh in "${SHRCDIR}"/*.sh; do
    # shellcheck source=/dev/null
    . "${sh}"
  done
fi
unset sh
unset SHRCDIR
