#!/bin/sh

# Shell-independent startup file for an interactive shell

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
SHRCDIR="${XDG_CONFIG_HOME}/sh/shrc.d"

if [ -d "${SHRCDIR}" ]; then
  for sh in "${SHRCDIR}"/*.sh; do
    # shellcheck source=/dev/null
    [ -e "${sh}" ] && . "${sh}"
  done
fi
unset sh
