#!/bin/bash -e
# install ncurses
(
_TEMPDIR=$(mktemp -d)
trap 'rm -rf -- "$_TEMPDIR"' EXIT
git clone --depth=1 https://github.com/mirror/ncurses.git "$_TEMPDIR"
cd "$_TEMPDIR" || exit 1
./configure --prefix="$HOME/.local"
make install
)

# install vim
(
_TEMPDIR=$(mktemp -d)
trap 'rm -rf -- "$_TEMPDIR"' EXIT
git clone --depth=1 https://github.com/vim/vim.git "$_TEMPDIR"
cd "$_TEMPDIR"/src || exit 1
./configure --prefix="$HOME/.local" --with-local-dir="$HOME/.local"
make install
)
