#!/bin/bash

# Bash startup file for an interactive shell
# For interactive login shell, ~/.bash_profile sources this file
# For remote shell daemon like ssh, ~/.bashrc is sourced directly

# shellcheck source=/dev/null
[ -f "${HOME}/.profile" ] && source "${HOME}/.profile"

# https://mise.jdx.dev/getting-started.html
if command -v mise > /dev/null 2>&1; then eval "$(mise activate bash)";fi

SHRC="${XDG_CONFIG_HOME}/sh/shrc"
# shellcheck source=/dev/null
[[ -e "${SHRC}" ]] && source "${SHRC}"

shopt -s globstar 2> /dev/null || true

unset PROMPT_COMMAND
BASHRCDIR="${XDG_CONFIG_HOME}/bash/bashrc.d"
if [[ -d "${BASHRCDIR}" ]]; then
  for sh in "${BASHRCDIR}"/*.bash; do
    # shellcheck source=/dev/null
    . "${sh}"
  done
  unset -v sh
fi
