#!/bin/bash
#
# Reference: https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html

# If not running interactively, don't do anything
case "$-" in
  *i*) ;;
  *) return 0 2>/dev/null || exit 0 ;;
esac

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
SHRC="${XDG_CONFIG_HOME}/sh/shrc"
# shellcheck source=/dev/null
[[ -e "${SHRC}" ]] && source "${SHRC}"

shopt -s checkwinsize globstar 2>/dev/null || true

unset PROMPT_COMMAND
BASHRCDIR="${XDG_CONFIG_HOME}/bash/bashrc.d"
if [[ -d "${BASHRCDIR}" ]]; then
  for sh in "${BASHRCDIR}"/*.bash; do
    # shellcheck source=/dev/null
    source "${sh}"
  done
  unset -v sh
fi
unset -v SHRC BASHRCDIR

# shellcheck source=/dev/null
[[ -f "${HOME}/.bashrc.local" ]] && source "${HOME}/.bashrc.local" 2>/dev/null || true
