#!/bin/bash

# Bash startup file for an interactive login shell
# Reference: https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

# shellcheck source=/dev/null
[[ -e "${HOME}/.profile" ]] && source "${HOME}/.profile"
# shellcheck source=/dev/null
[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"
