# shellcheck shell=bash
#
# Reference: https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

# shellcheck source=/dev/null
[[ -e "${HOME}/.profile" ]] && source "${HOME}/.profile"

__pathmunge "${HOME}/.local/share/mise/shims"

for _brew_prefix in "${HOMEBREW_PREFIX:-}" /opt/homebrew /usr/local /home/linuxbrew/.linuxbrew; do
  if [[ -n "${_brew_prefix}" && -x "${_brew_prefix}/bin/brew" ]]; then
    __cached "${_brew_prefix}/bin/brew" shellenv
    break
  fi
done
unset _brew_prefix

__pathmunge "${HOME}/.local/bin"

# shellcheck source=/dev/null
[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"
