#!/bin/bash

# shellcheck source=/dev/null
[[ -f "${HOME}/.profile" ]] && source "${HOME}/.profile"

SHRC="${XDG_CONFIG_HOME}/sh/shrc"
# shellcheck source=/dev/null
[[ -e "${SHRC}" ]] && source "${SHRC}"

shopt -s globstar 2> /dev/null || true

unset PROMPT_COMMAND
BASHRCDIR="${XDG_CONFIG_HOME}/bash/bashrc.d"
if [[ -d "${BASHRCDIR}" ]]; then
  for sh in "${BASHRCDIR}"/*.bash; do
    # shellcheck source=/dev/null
    . "${sh}"
  done
  unset -v sh
fi

. "${HOME}/.bashrc.local" 2> /dev/null || true
