#!/bin/bash
#
# Reference:
# - https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

ESC=$(printf '\033')
payload=$(cat | sed "s/${ESC}/${ESC}${ESC}/g")
printf "${ESC}Ptmux;%s${ESC}\\${ESC}\\" "$payload"
