brew "mas"
cask "battle-net"
cask "discord"
cask "fliqlo"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "gureumkim"
cask "hammerspoon"
cask "minecraft"
cask "steam"
cask "ubersicht"
cask "visual-studio-code"
cask "wezterm"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
