#!/usr/bin/env sh
mkdir -v ~/Library/Application\ Support/Übersicht/widgets/morning.widget
curl https://raw.githubusercontent.com/imRohan/ubersicht-morning.widget/master/morning.widget/morning.coffee --output ~/Library/Application\ Support/Übersicht/widgets/morning.widget/morning.coffee
