" ~/.vim/vimrc
" It needs Vim 8.0 to use packadd
" Anyway, read https://www.vi-improved.org/recommendations/

" Set nocompatible {{{1
if &g:compatible
  set nocompatible
endif

" Add external packages {{{1
packadd dracula
packadd vim-gitgutter
packadd vim-dirvish
packadd vim-fugitive

" termguicolors, etc... {{{1
set termguicolors
let &t_8f="\<esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<esc>[48;2;%lu;%lu;%lum"

" Customize Dracula {{{1
augroup dracula_customization
  autocmd!
  autocmd ColorScheme dracula
        \ highlight Normal guibg=NONE ctermbg=NONE
        \|highlight DraculaComment cterm=italic
        \|highlight link VertSplit DraculaCommentBold
        \|highlight VertSplit guibg=NONE ctermbg=NONE gui=None cterm=None
        \|highlight link FoldColumn DraculaCommentBold
        \|highlight link PmenuSel WildMenu
augroup END
colorscheme dracula

" GitGutter Settings {{{1
augroup gitgutter_listener
  autocmd!
  autocmd User GitGutter let &l:statusline=&l:statusline
augroup END

" Comment map {{{1
" TODO: unify these
function! SetPythonCommentMap() abort
  nnoremap <leader>c<space> mcI# <esc>`c
  vnoremap <leader>c<space> :s\/^\/#\

  nnoremap gcc mcI# <esc>`c
  vnoremap gc :s\/^\/#\
endfunction

augroup commentmap
  autocmd!
  autocmd FileType javascript
        \ nnoremap <leader>c<space> mcI// <esc>`c
  autocmd FileType c
        \ nnoremap <leader>c<space> mcI// <esc>`c
  autocmd FileType cpp
        \ nnoremap <leader>c<space> mcI// <esc>`c
augroup END

" Miscellaneous settings {{{1
set number
set relativenumber
" set background=dark
set nowrap
set hlsearch
set hidden
set ignorecase
set smartcase
set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab
set list
let &showbreak = '> '
set belloff=all
set showcmd

cabbr <expr> %% expand('%:p:h')

vnoremap < <gv
vnoremap > >gv
vnoremap * y/<c-r>"<cr>

" nnoremap Q @q
nnoremap Y y$

" nnoremap n nzz
" nnoremap N Nzz

" Leader maps {{{1
" nnoremap <leader>b :b<space><c-d>
nnoremap <leader>b :ls<cr>:b<space>
nnoremap <silent> <leader>m :make!<cr>
" TODO: The below ruins last search pattern register
nnoremap <silent> <leader>s mzHmy:%s/\s\+$//e<cr>'yz<cr>`z:noh<cr>
nnoremap <silent> <leader>q :b#<cr>
nnoremap <silent> <leader>= mzHmygg=G'yz<cr>`z

" Set text width 80 {{{1
if exists('&colorcolumn')
  set colorcolumn=81
endif
" set textwidth=79

" Pop-up menu {{{1
" set completeopt=noinsert,preview,menuone
" set pumheight=5

" Completion settings "{{{1
augroup completion
  "TODO
  autocmd!
  "autocmd CursorMovedI * execute('if pumvisible() normal! a')
augroup END

" Set backup, spellcheck, swap and undo {{{1
set spell
set undofile

let &backupdir = expand('~/.local/share/vim/backup/')
let &spellfile = expand('~/.local/share/vim/spell/en.utf-8.add')
let &directory = expand('~/.local/share/vim/swap/')
let &undodir = expand('~/.local/share/vim/undo/')

if !isdirectory(&backupdir) | call mkdir(&backupdir, 'p') | endif
let s:spelldir = fnamemodify(&spellfile, ':p:h')
if !isdirectory(s:spelldir) | call mkdir(s:spelldir, 'p') | endif
unlet s:spelldir
if !isdirectory(&directory) | call mkdir(&directory, 'p') | endif
if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif

let g:netrw_home = expand('~/.local/share/vim/')

" Set fold (zR/zM to open/close all folds) {{{1
set foldcolumn=1
if v:version < 802
  set fillchars+=vert:│
else
  set fillchars+=vert:│,foldsep:│,foldopen:┌
endif

" Set syntax sync {{{1
syntax sync fromstart

" Netrw settings {{{1
let g:netrw_fastbrowse = 0
let g:netrw_winsize = 30
let g:netrw_banner = 0

" }}}
" vim:ft=vim:fdm=marker:ts=2:sts=2:sw=2:fdl=0
