" ~/.vim/vimrc
" :help :help
" https://learnvimscriptthehardway.stevelosh.com
" https://learnvim.irian.to

if &g:compatible
  set nocompatible
endif

" custom wrapper function for minpac#add with opt type
" https://github.com/k-takata/minpac/issues/113
function! s:pac_add(url, ...) abort
  let l:options = get(a:000, 0, {})
  call minpac#add(a:url, extend({'type': 'opt'}, l:options, 'force'))
endfunction

silent! packadd minpac
if exists('g:loaded_minpac')
  function! s:PackInit() abort
    packadd minpac

    call minpac#init()
    call s:pac_add('k-takata/minpac')

    call s:pac_add('tpope/vim-abolish')
    call s:pac_add('tpope/vim-commentary')
    call s:pac_add('tpope/vim-repeat')
    call s:pac_add('tpope/vim-surround')

    call s:pac_add('airblade/vim-gitgutter')
    call s:pac_add('tpope/vim-fugitive')
    call s:pac_add('justinmk/vim-dirvish')

    call s:pac_add('prabirshrestha/vim-lsp')
    call s:pac_add('mattn/vim-lsp-settings')

    call s:pac_add('prabirshrestha/asyncomplete.vim')
    call s:pac_add('prabirshrestha/asyncomplete-lsp.vim')

    call s:pac_add('sheerun/vim-polyglot')

    call s:pac_add('github/copilot.vim')

    call s:pac_add('junegunn/fzf',
          \ {'do': 'silent! packadd fzf | call fzf#install()'})
    call s:pac_add('junegunn/fzf.vim')

    call s:pac_add('ryanoasis/vim-devicons')
  endfunction

  command! PackUpdate source $MYVIMRC | call s:PackInit() | call minpac#update()
  command! PackClean  source $MYVIMRC | call s:PackInit() | call minpac#clean()
  command! PackStatus packadd minpac | call minpac#status()
endif

" Source files in vimrc.d/preload
for s:f in split(glob('~/.vim/vimrc.d/preload/*.vim'), '\n')
  execute 'source' s:f
endfor

silent! packadd vim-abolish
silent! packadd vim-commentary
silent! packadd vim-repeat
silent! packadd vim-surround

silent! packadd vim-gitgutter
silent! packadd vim-fugitive
silent! packadd vim-dirvish

silent! packadd vim-lsp
silent! packadd vim-lsp-settings

silent! packadd asyncomplete.vim
silent! packadd asyncomplete-lsp.vim

" silent! packadd vim-polyglot

silent! packadd copilot.vim

silent! packadd fzf
silent! packadd fzf.vim

silent! packadd vim-devicons

silent! packadd bufferline
silent! packadd sensible
silent! packadd statusline
silent! packadd unimpaired
silent packadd vim-scriptease

silent! colorscheme dracula16

" Source files in vimrc.d
for s:f in split(glob('~/.vim/vimrc.d/*.vim'), '\n')
  execute 'source' s:f
endfor

" :help 'termguicolors'
" if has('termguicolors') | set termguicolors | endif

" :help xterm-true-color
" let &t_8f="\<esc>[38;2;%lu;%lu;%lum"
" let &t_8b="\<esc>[48;2;%lu;%lu;%lum"

" :help termcap-cursor-shape
if &term =~ "xterm"
  let &t_SI="\<esc>[5 q" " blinking bar
  let &t_SR="\<esc>[3 q" " blinking underline
  let &t_EI="\<esc>[0 q" " block
endif
augroup termcap_cursor_shape
  autocmd!
  autocmd VimEnter * silent !echo -ne "\e[0 q"
augroup END

" https://github.com/vim/vim/commit/e07e797db0c5ef1aafc650d8bb0d39fb052cf1e1
set ttimeout
set ttimeoutlen=100

" :help section
map [[ ?{<cr>w99[{
map ][ /{<cr>b99[{
map ]] j0[[%/{<cr>
map [] k$][%?}<cr>

" :help 'colorcolumn'
if exists('&colorcolumn') | set colorcolumn=81 | endif

" :help :helptags
silent! helptags ALL

set number
set relativenumber
set ignorecase
set smartcase
if has('persistent_undo') | set undofile | endif
set list
set visualbell
if has('syntax') | set spell | endif
set nowrap

let &spellfile = expand('$HOME/.local/share/vim/spell/en.utf-8.add')
let s:spelldir = fnamemodify(&spellfile, ':p:h')
if !isdirectory(s:spelldir) | call mkdir(s:spelldir, 'p') | endif
unlet s:spelldir

cabbr <expr> %% expand('%:p:h')

xnoremap < <gv
xnoremap > >gv
nnoremap <silent> <leader>= mzHmygg=G'yz<cr>`z

" nnoremap <leader>y "+y
" nnoremap <leader>d "+d
" nnoremap <leader>p "+p
" xnoremap <leader>y "+y
" xnoremap <leader>d "+d
" xnoremap <leader>p "+p

if !has('nvim')
  augroup terminal_win_open
    autocmd!
    autocmd TerminalWinOpen *
          \ setlocal nobuflisted
          \|setlocal nospell
          \|setlocal colorcolumn=
  augroup end
endif

" source host-local vimrc
let s:vimrc_host = expand('$HOME/.vimrc.host')
if filereadable(s:vimrc_host) | execute "source " . s:vimrc_host | endif
setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab

" :help last-pattern
command! Reload source $MYVIMRC | let @/ = ""

nnoremap <leader>rr :Reload<cr>
