" ~/.vim/vimrc
" :help :help
" https://learnvimscriptthehardway.stevelosh.com
" https://learnvim.irian.to

"" https://neovim.io/doc/user/vim_diff.html
filetype plugin indent on

set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
" $XDG_STATE_HOME/vim/backup
set backupdir=~/.local/state/vim/backup
set belloff=all
set nocompatible
set complete-=i
" $XDG_STATE_HOME/vim/swap
set directory=~/.local/state/vim/swap
set display=lastline
set encoding=utf-8
scriptencoding utf-8
" set fillchars=vert:│,fold:·,sep:│
set fillchars=vert:│,foldopen:-,foldclose:+
set formatoptions=tcqj
set nofsync
set hidden
set history=10000
set hlsearch
set incsearch
set nojoinspaces
set langnoremap
set nolangremap
set laststatus=2
set listchars=tab:>\ \ ,trail:-,nbsp:+
set mouse=nvi
set mousemodel=popup_setpos
set nrformats=bin,hex
set ruler
set sessionoptions+=unix,slash sessionoptions-=options
set shortmess+=F shortmess-=S
set showcmd
set sidescroll=1
set smarttab
set nostartofline
set switchbuf=uselast
set tabpagemax=50
set tags=./tags;,tags " :help file-searching
set ttimeoutlen=50
set undodir=~/.local/state/nvim/undo
set viewoptions+=unix,slash viewoptions-=options
set viminfo+=!
set wildmenu
set wildoptions=pum,tagfile

packadd! matchit
let g:vimsyn_embed='l'

if !isdirectory(&backupdir) | call mkdir(&backupdir, 'p') | endif
if !isdirectory(&directory) | call mkdir(&directory, 'p') | endif
if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif

nnoremap Y y$
" :help <cmd>
nnoremap <c-l> <cmd>nohlsearch<bar>diffupdate<bar>normal! <c-l><cr>
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>
" :help /\V
xnoremap * y/\V<c-r>"<cr>
xnoremap # y?\V<c-r>"<cr>
nnoremap & :&&<cr>

" NOTE: In nvim, `Q` replays the last recorded macro.
nnoremap Q @@
nnoremap gQ Q

"" https://www.vi-improved.org/recommendations/

function! s:StripTrailingWhitespace()
  if !&binary && &filetype != 'diff'
    normal mz
    normal Hmy
    %s/\s\+$//e
    normal 'yz<CR>
    normal `z
  endif
endfunction
command StripTrailingWhitespace call s:StripTrailingWhitespace()

nnoremap <leader>a
      \ :<c-u>argadd <c-r>=filenameescape(expand('%:p:h'))<cr>/*<c-d>
nnoremap <leader>b :<c-u>ls<cr>:b <c-d>
nnoremap <leader>e :<c-u>e **/
nnoremap <leader>g :<c-u>greap<space>
" nnoremap <leader>i :Ilist<space>
nnoremap <leader>j :<c-u>tjump /
nnoremap <leader>m :<c-u>make<cr>
nnoremap <leader>s :<c-u>StripTrailingWhitespace<cr>
nnoremap <leader>q :b#<cr>

""

set undofile

" vim: set ft=vim fdm=marker ts=2 sts=2 sw=2 fdl=0:
