#!/bin/bash

# Bash startup file for an interactive shell
# ~/.bash_profile sources this file

SHRC="${XDG_CONFIG_HOME}/sh/shrc"
# shellcheck source=/dev/null
[[ -e "${SHRC}" ]] && source "${SHRC}"

shopt -s globstar 2> /dev/null || true
[ "$(uname -s)" == 'Darwin' ] && export BASH_SILENCE_DEPRECATION_WARNING=1

mkdir -p "${XDG_STATE_HOME}"/bash
export HISTFILE="${XDG_STATE_HOME}/bash/history"

BASHRCDIR="${XDG_CONFIG_HOME}/bash/bashrc.d"
if [[ -d "${BASHRCDIR}" ]]; then
  for sh in "${BASHRCDIR}"/*.bash; do
    # shellcheck source=/dev/null
    . "${sh}"
  done
  unset -v sh
fi

# shellcheck source=/dev/null

# https://github.com/nvm-sh/nvm?tab=readme-ov-file#bash-completion
. "$NVM_DIR/bash_completion" 2> /dev/null

# https://github.com/junegunn/fzf
if [ command -v fzf > /dev/null 2>&1 ]; then eval "$(fzf --bash)"; fi

# https://github.com/ajeetdsouza/zoxide
if [ command -v zoxide > /dev/null 2>&1 ]; then eval "$(zoxide init bash)"; fi
