#!/bin/sh

# POSIX shell startup file for an interactive login shell

# : "${XDG_BIN_HOME:="${HOME}/.local/bin"}"
# : "${XDG_CONFIG_HOME:="${HOME}/.config"}"
# : "${XDG_STATE_HOME:="${HOME}/.local/state"}"
# : "${XDG_CACHE_HOME:="${HOME}/.cache"}"

export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="${HOME}/.cache"

[ -e "${HOME}/.shenv" ] && ENV="${HOME}/.shenv"
# shellcheck source=/dev/null
[ -n "${ENV}" ] && . "${ENV}"

set -o allexport
[ -e "${HOME}/.env" ] && . "${HOME}/.env"
set +o allexport

PATH=${XDG_BIN_HOME}:$PATH
export PATH

PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig:${PKG_CONFIG_PATH}"
PKG_CONFIG_PATH="${HOME}/.local/lib64/pkgconfig:${PKG_CONFIG_PATH}"
export PKG_CONFIG_PATH

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/lib"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/lib64"
export LD_LIBRARY_PATH

# Export editors
export EDITOR='vim -E'
export PAGER='less'
export VISUAL='vim'

# Cygwin environment variables
# https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
export CYGWIN=winsymlinks:nativestrict
export MSYS="${CYGWIN}"
