#!/bin/sh
# Shell-independent startup file for an interactive shell

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
if [ -f "${XDG_CONFIG_HOME}/sh/env.sh" ]; then
  # shellcheck source=/dev/null
  . "${XDG_CONFIG_HOME}/sh/env.sh"
fi

SHRCDIR="${XDG_CONFIG_HOME}/sh/shrc.d"
if [ -d "${SHRCDIR}" ]; then
  for sh in "${SHRCDIR}"/*.sh; do
    # shellcheck source=/dev/null
    [ -f "${sh}" ] && . "${sh}"
  done
fi
unset sh

if [ -n "${WEZTERM_EXECUTABLE:-}" ]; then
  export WEZTERM_SHELL="${SHELL}"
fi
unset SHRCDIR
