#!/bin/sh
# Shell-independent startup file for an interactive shell

: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
SHRCDIR="${XDG_CONFIG_HOME}/sh/shrc.d"
if [ -d "${SHRCDIR}" ]; then
  for sh in "${SHRCDIR}"/*.sh; do
    # shellcheck source=/dev/null
    . "${sh}"
  done
fi
unset sh

if [ -n "${WEZTERM_EXECUTABLE}" ]; then
  export WEZTERM_SHELL="${SHELL}"
else
  # if [ -f "${XDG_STATE_HOME}"/sh/colors.sh ]; then
  #   # shellcheck source=/dev/null
  #   case $- in
  #     *i*) . "${XDG_STATE_HOME}"/sh/colors.sh ;;
  #   esac
  # fi
fi

if [ -f "${HOME}/.env" ]; then
  . "${HOME}/.env"
fi
unset SHRCDIR
