#!/bin/sh

set -o nounset
set -o errexit

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
readonly BASE_DIR

# shellcheck source=scripts/lib.sh
. "${BASE_DIR}/scripts/lib.sh"

if [ $# -lt 1 ]; then
  die "Usage: $0 <sh|bash|zsh> [flags...]"
fi

shell="$1"
shift 1

case "${shell}" in
zsh)
  zsh --sourcetrace "$@" -c exit 2>&1 | awk -F'[:<]' '{sub(/^\+/, "", $1); print $1}'
  ;;
bash)
  bash -x "$@" -c exit 2>&1 | grep -E '^\+* *(source|\.) ' | awk '{print $NF}'
  ;;
sh)
  sh -x "$@" -c exit 2>&1 | grep -E '^\+* *(source|\.) ' | awk '{print $NF}'
  ;;
*)
  die "Unsupported shell: ${shell}"
  ;;
esac
