#!/bin/sh

set -o nounset
set -o errexit

if [ $# -lt 1 ]; then
  echo "Usage: $0 <bash|zsh> [flags...]" >&2
  exit 1
fi

shell="$1"
shift 1

if [ $# -eq 0 ]; then
  set -- -l -i
fi

case "${shell}" in
zsh | bash)
  ;;
*)
  echo "Unsupported shell: ${shell}" >&2
  exit 2
  ;;
esac

case "${shell}" in
zsh)
  zsh --sourcetrace "$@" -c exit 2>&1
  ;;
bash)
  PS4='+${BASH_SOURCE[0]}:${LINENO}> ' bash -x "$@" -c exit 2>&1
  ;;
*)
  exit 1
  ;;
esac |
  LC_ALL=C sed -E -n 's/^\++(.*):[0-9]+> .*$/\1/p' |
  awk '!seen[$0]++ && /^\//' |
  paste -sd: -
