#!/bin/sh

set -o nounset
set -o errexit

export __DOTFILES_UPGRADE=1

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
readonly BASE_DIR

# shellcheck source=scripts/lib.sh
. "${BASE_DIR}/scripts/lib.sh"

OS="$(detect_os)"
ARCH="$(detect_arch)"
export OS ARCH
readonly OS ARCH

run_hook pre-upgrade

# shellcheck disable=SC2310
if has brew; then
  brew update
  brew upgrade
fi

# shellcheck disable=SC2310
if has mise; then
  mise upgrade --bump
fi

# shellcheck disable=SC2310
if has prek; then
  prek update
fi
# shellcheck disable=SC2310
if has nvim; then
  nvim --headless \
    -c "lua vim.pack.update(nil, { force = true })" \
    -c "qall!"
fi

run_hook post-upgrade
