#!/bin/zsh
# ${HOME}/Library/Preferences/
# TODO: Move more settings from System Settings to this script

################################################################################
# Finder
################################################################################
# ... > cmd + shift + .
defaults write com.apple.finder AppleShowAllFiles -bool true
# ... > Settings > General > Show these items on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
# ... > View > Show Status Bar, Show Path Bar
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder ShowPathbar -bool true
killall Finder
################################################################################


################################################################################
# TextEdit
################################################################################
# ... > Settings > New Document > Format > Plain text
defaults write com.apple.TextEdit RichText -int 0
# defaults write com.apple.TextEdit PlainTextEncoding -int 4
# defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4
################################################################################


################################################################################
# Dock
################################################################################
# System Settings > Dock & Menu Bar
# ... > Automatically hide and show the Dock (enable)
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock persistent-apps -array ''
# ... > Hot Corners... > Top Left Corner > No Action
# defaults write com.apple.dock wvous-bl-corner -int 0
killall Dock
################################################################################


################################################################################
# Screen Capture
################################################################################
# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true
################################################################################



################################################################################
# Global Preferences
################################################################################
# Finder
################################################################################
# ... > Settings > Advanced > Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
################################################################################
# System Settings > Keyboard
################################################################################
# ... > Text Input > Text Replacements... (clear all)
defaults write NSGlobalDomain NSUserDictionaryReplacementItems -array '()'
# ... > Input Sources > Correct spelling automatically (disable)
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
# ... > Input Sources > Capitalize words automatically (disable)
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
# ... > Input Sources > Add period with double-space (disable)
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
# ... > Input Sources > Use smart quotes and dashes (disable)
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
################################################################################

# sudo nvram SystemAudioVolume=" "

# defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# defaults write NSGlobalDomain AppleShowScrollBars -string "Automatic"

# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
# defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# defaults write com.apple.LaunchServices LSQuarantine -bool false

# /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

# defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# defaults write com.apple.helpviewer DevMode -bool true

# sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
# defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
# defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
# defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true

# sudo systemsetup -settimezone "Asian/Seoul" > /dev/null

# sudo rm /private/var/vm/sleepimage
# sudo touch /private/var/vm/sleepimage
# sudo chflags uchg /private/var/vm/sleepimage

# Screen
# defaults write NSGlobalDomain AppleFontSmoothing -int 1
# sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# Finder
# defaults write com.apple.finder QuitMenuItem -bool true

# defaults write com.apple.finder NewWindowTarget -string "PfDe"
# defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
# defaults write com.apple.finder _FXSortFoldersFirst -bool true
# defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# defaults write NSGlobalDomain com.apple.springing.enabled -bool true
# defaults write NSGlobalDomain com.apple.springing.delay -float 0

# defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
# defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# defaults write com.apple.frameworks.diskimages skip-verify -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
# defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
# defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# defaults write NSGlobalDomain _HIHideMenuBar -bool true
# defaults write com.apple.menuextra.clock DateFormat -string "EEE MMM d  HH:mm:ss a"
# defaults write com.apple.systemuiserver menuExtras -array \
# "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
# "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
# "/System/Library/CoreServices/Menu Extras/Clock.menu" \
# "/System/Library/CoreServices/Menu Extras/Displays.menu" \
# "/System/Library/CoreServices/Menu Extras/Volume.menu"

# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 80" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 80" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 80" ~/Library/Preferences/com.apple.finder.plist

# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 60" ~/Library/Preferences/com.apple.finder.plist

# defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# defaults write com.apple.finder WarnOnEmptyTrash -bool false

# chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library
# sudo chflags nohidden /Volumes

# defaults write com.apple.finder FXInfoPanesExpanded -dict \
# 	General -bool true \
# 	OpenWith -bool true \
# 	Privileges -bool true

# # Dock, Dashboard
# defaults write com.apple.dock '{
#     "autohide" = true;
#     "autohide-delay" = 0;
#     "dashboard-in-overlay" = true;
#     "enable-spring-load-actions-on-all-items" = 1;
#     "mouse-overhilite-stack" = true;
#     "orientation = bottom";
#     "persistent-apps" = -array ();
#     "persistent-others" = -array ();
#     "recent-apps" = -array ();
#     "show-recents" = false;
#     "showhidden" = 1;
#     "tilesize" = 56;
# }'

# defaults write com.apple.dashboard mcx-disabled -bool true

# Activity Monitor
# defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
# defaults write com.apple.ActivityMonitor IconType -int 5
# defaults write com.apple.ActivityMonitor ShowCategory -int 0
# defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
# defaults write com.apple.ActivityMonitor SortDirection -int 0

# Photos
# defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

# # iTerm 2
# open "${HOME}/init/iterm/Dracula.itermcolors"
# defaults write com.googlecode.iterm2 PromptOnQuit -bool false

# Kill affected applications
# for app in "Activity Monitor" \
# 	"cfprefsd" \
# 	"Contacts" \
# 	"Dock" \
# 	"Finder" \
# 	"Photos" \
# 	"SizeUp" \
# 	"SystemUIServer"; do
# 	killall "${app}" &> /dev/null
# done
# echo "Done. Note that some of these changes require a logout/restart to take effect."
