# Reference: https://mise.jdx.dev/configuration.html
[tools]
bat = "latest"
bats = "latest"
bottom = "latest"
bun = "latest"
cmake = "latest"
deno = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
java = "temurin"
jq = "latest"
lsd = "latest"
lua-language-server = "latest"
marksman = "latest"
neovim = "latest"
ninja = "latest"
node = "latest"
pandoc = "latest"
"pipx:huggingface_hub[cli]" = "latest"
prek = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
stylua = "latest"
taplo = "latest"
tinytex = "latest"
tmux = "latest"
tree-sitter = "latest"
ty = "latest"
uv = "latest"
vim = "latest"
zoxide = "latest"
"aqua:tummychow/git-absorb" = "latest"
"github:leejet/stable-diffusion.cpp" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:bash-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-html-languageserver-bin" = "latest"
"npm:yaml-language-server" = "latest"
