[tools]
bat = "latest"
bottom = "latest"
cmake = "latest"
delta = "latest"
deno = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
java = "zulu"
jq = "latest"
lsd = "latest"
marksman = "latest"
neovim = "latest"
ninja = "latest"
node = "latest"
"npm:vscode-html-languageserver-bin" = "latest"
pandoc = "latest"
prek = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
stylua = "latest"
tinytex = "latest"
tmux = "latest"
ty = "latest"
uv = "latest"
vim = "latest"
zoxide = "latest"
"aqua:tummychow/git-absorb" = "latest"
"github:leejet/stable-diffusion.cpp" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
