# Reference: https://mise.jdx.dev/configuration.html

[tools]
"aqua:mattn/efm-langserver" = "0.0.57"
"aqua:tmux/tmux-builds" = "3.7c"
bat = "0.26.1"
bats = "1.14.0"
biome = "2.5.15"
bottom = "0.14.9"
bun = "1.4.2"
cmake = "4.4.4"
deno = "2.9.7"
fd = "10.5.0"
fzf = "0.74.4"
gh = "2.102.0"
java = "27"
jq = "1.8.2"
lsd = "1.2.0"
lua-language-server = "3.19.1"
marksman = "2026-02-08"
neovim = "0.12.5"
ninja = "1.13.2"
node = "26.10.0"
"npm:@colbymchenry/codegraph" = "1.6.2"
"npm:@earendil-works/pi-coding-agent" = "1.0.4"
"npm:bash-language-server" = "5.8.1"
"npm:markdownlint-lsp" = "0.10.0"
"npm:vim-language-server" = "2.3.1"
"npm:vscode-html-languageserver-bin" = "1.4.0"
"npm:yaml-language-server" = "1.24.0"
pandoc = "3.12"
"pipx:huggingface_hub" = "2.1.1"
"pipx:huggingface_hub[cli]" = "1.29.0"
"pipx:yamllint" = "1.38.0"
prek = "0.5.5"
python = "3.14.8"
ripgrep = "15.2.0"
ruff = "0.16.10"
rust = "1.99.0"
shellcheck = "0.11.0"
shfmt = "3.14.1"
stylua = "2.5.2"
taplo = "0.10.0"
tinytex = "2026.10"
tree-sitter = "0.27.0"
ty = "0.0.84"
uv = "0.12.23"
vim = "9.2.1169"
zoxide = "0.10.0"
