[[items]]
file = "${XDG_STATE_HOME:-~/.local/state}/sh/colors.sh"
rewrite = true
template = "shell"

[[items]]
file = "${XDG_STATE_HOME:-~/.local/state}/wezterm/colorschemes/colors.toml"
rewrite = true
template = "wezterm"

[[items]]
file = "${XDG_CONFIG_HOME:-~/.config}/ghostty/themes/flavours"
rewrite = true
template = "ghostty"

[[items]]
file = "${XDG_STATE_HOME:-~/.local/state}/alacritty/colors.toml"
rewrite = true
template = "alacritty"
