# Set prefix (C-a)
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Source files in .tmux.conf.d
source-file ~/.tmux.conf.d/*

# Set server options
set-option -s escape-time 0

# Set global session options
set-option -g history-limit 50000
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g pane-base-index 1

bind-key r source-file ~/.tmux.conf \; display-message "source-file done"
bind-key y set-window-option synchronize-panes


# vim:ts=2:sts=2:sw=2:et:sta:fdm=marker:fdl=0
