# Dracula Color Pallette
# https://spec.draculatheme.com/
background='#282a36'
foreground='#f8f8f2'
selection='#44475a'
comment='#6272a4'

red='#ff5555'
orange='#ffb86c'
yellow='#f1fa8c'
green='#50fa7b'
purple='#bd93f9'
cyan='#8be9fd'
pink='#ff79c6'

# border style
set-option -g pane-active-border-style "fg=${purple}"
set-option -g pane-border-style "fg=${selection}"

# message, status style
set-option -g message-style "bg=${selection},fg=${foreground}"
set-option -g display-time 4000
set-option -g status-style "bg=${selection},fg=${foreground}"
set-option -g status-interval 5

# status left
set-option -g status-left-length 100
set-option -g status-left \
"#[bg=#{?client_prefix,${yellow},${green}},fg=${background}] #{session_name} "

# window status
set-option -g window-status-current-format \
"#[bg=${background},fg=${foreground}] #I #W#F "
set-option -g window-status-format \
"#[bg=${selection},fg=${foreground}] #I #W#F "
set-option -g window-status-separator ""

set-option -g window-status-activity-style "bold"
set-option -g window-status-bell-style "bold"

# status right
set-option -g status-right-length 100
set-option -g status-right \
"#[bg=${cyan},fg=${background}] #{pane_title} \
#[bg=${orange},fg=${background}] %H:%M %Y-%m-%d "

# server options
set-option -s escape-time 0

# global session options
set-option -g history-limit 50000
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g pane-base-index 1
set-option -g default-terminal "screen-256color"
set-option -as terminal-overrides ",*256col*:Tc"

# navigate pane
bind-key h select-pane -L
bind-key C-h select-pane -L
bind-key j select-pane -D
bind-key C-j select-pane -D
bind-key k select-pane -U
bind-key C-k select-pane -U
bind-key l select-pane -R
bind-key C-l select-pane -R

# vim-like resize pane
bind-key -r - resize-pane -D 5
bind-key -r + resize-pane -U 5
bind-key -r < resize-pane -L 5
bind-key -r > resize-pane -R 5

# resize pane 
# bind-key -r H resize-pane -L 5
# bind-key -r J resize-pane -D 5
# bind-key -r K resize-pane -U 5
# bind-key -r L resize-pane -R 5

# split window with a current path
bind-key "%" split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"
# bind-key "c" new-window -c "#{pane_current_path}"

# navigate window
bind-key C-p previous-window
bind-key C-n next-window

# vim-like visual mode
bind-key Escape copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind-key -T copy-mode-vi Escape send-keys -X cancel # TODO: add feature
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# unbind p
bind-key P paste-buffer
bind-key C-r choose-buffer

# vi keys
set-option -g status-keys vi
set-option -g mode-keys vi

# last window
bind-key b last-window

# source-file
bind-key r source-file ~/.tmux.conf \; display-message " source-file done"

# miscellaneous key binding
bind-key y set-window-option synchronize-panes

# tmux-in-tmux
# prefix C-a to disable outmost tmux, C-a C-a to enable it.
bind-key C-a \
    set-option key-table disabled\; \
    set-option prefix None\; \
    set-option status-left "#[bg=${comment},fg=${background}] #{session_name}[D] "\; \
    set-option status-right "#[bg=${comment},fg=${background}] #{pane_title} "\; \
    set-option window-status-current-format "#[bg=${background},fg=${comment}] #I #W#F "\; \
    set-option status-interval 0\;

bind-key -T disabled C-a \
    set-option key-table _disabled

# TODO: color for _disabled mode
bind-key -T _disabled C-a \
    set-option -u key-table\; \
    set-option -u prefix\; \
    set-option -u status-left\; \
    set-option -u status-right\; \
    set-option -u window-status-current-format\; \
    set-option -u status-interval\;

# vim:ts=2:sts=2:sw=2:et:sta:fdm=marker:fdl=0
