[tools]
bat = "latest"
"npm:@google/gemini-cli" = "latest"
ruff = "latest"
ty = "latest"
uv = "latest"
cmake = "latest"
fzf = "latest"
gh = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
tmux = "latest"
