#!/bin/zsh

# Zsh startup file for an interactive shell

: ${XDG_CONFIG_HOME:="${HOME}/.config"}
SHRC="${XDG_CONFIG_HOME}/sh/shrc"
[[ -e "${SHRC}" ]] && source "${SHRC}"

: ${ZDOTDIR:=${XDG_CONFIG_HOME}/zsh}
ZSHRCDIR="${ZDOTDIR}/zshrc.d"
if [[ -d "${ZSHRCDIR}" ]]; then
  for sh in "${ZSHRCDIR}"/*.zsh; do
    [[ -e "${sh}" ]] && source "${sh}"
  done
  unset -v sh
fi

# https://github.com/junegunn/fzf
if command -v fzf > /dev/null 2>&1; then eval "$(fzf --zsh)"; fi

# https://github.com/ajeetdsouza/zoxide
if command -v zoxide > /dev/null 2>&1; then eval "$(zoxide init zsh)"; fi

# https://github.com/pyenv/pyenv
if command -v pyenv > /dev/null 2>&1; then eval "$(pyenv init - zsh)"; fi
