# Reference: https://mise.jdx.dev/configuration.html

[tools]
"aqua:tmux/tmux-builds" = "3.7c"
bat = "0.26.1"
bats = "1.14.0"
bottom = "0.14.9"
cmake = "4.4.4"
fd = "10.5.0"
fzf = "0.74.4"
gh = "2.102.0"
jq = "1.8.2"
lsd = "1.2.0"
neovim = "0.12.5"
ninja = "1.13.2"
pandoc = "3.12"
ripgrep = "15.2.0"
shellcheck = "0.11.0"
shfmt = "3.14.1"
tree-sitter = "0.27.0"
vim = "9.2.1169"
zoxide = "0.10.0"
