# Set prefix (C-a)
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
bind-key a last-window

# Set mouse
set-option -g mouse on

source-file "${XDG_CONFIG_HOME}/tmux/tmux.conf.d/*"

# Set vi mode
set-option -g mode-keys vi

# Set global session options
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g pane-base-index 1

bind-key y set-window-option synchronize-panes
