source-file "${XDG_CONFIG_HOME}/tmux/tmux.conf.d/*"

set-option -g prefix C-a

set-option -g default-terminal "tmux-256color"
set-option -g escape-time 0
set-option -g mode-keys vi
set-option -g mouse on
set-option -g status-keys emacs

set-option -g bell-action other
set-option -g monitor-bell on

set-option -g renumber-windows on
set-option -g allow-passthrough on

bind-key C-a send-prefix
bind-key a last-window

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5
bind-key -r C-l resize-pane -R 5

bind-key @ join-pane -t !

bind-key y set-window-option synchronize-panes

# Overwrite the default key bindings
bind-key \; select-pane -lZ
bind-key '%' split-window -h -c "#{pane_current_path}" -h
bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

bind-key R source-file "${XDG_CONFIG_HOME}"/tmux/tmux.conf \; \
	display-message "source-file done"
