#!/bin/bash
set nounset
set errexit

tmpdir=$(mktemp -d)
trap 'rm -rf -- "${tmpdir}"' EXIT
git clone --depth=1 https://github.com/python/cpython.git "${tmpdir}"
cd "${tmpdir}"
./configure --prefix="$HOME/.local"
make install
