#!/bin/bash

tmpdir=$(mktemp -d)
trap 'rm -rf -- "${tmpdir}"' EXIT
git clone --depth=1 https://github.com/mirror/ncurses.git "${tmpdir}"
cd "${tmpdir}" || exit 1
./configure --prefix="$HOME/.local"
make install
