#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
mkdir -p "${XDG_DATA_HOME}"
curl -H "Accept: application/vnd.github.v3+json" \
  "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh" \
  -s -o "${XDG_DATA_HOME}/git-prompt.sh"
